### ISSUE TITLE
tag for "heatsources"

### ISSUE THREAD

**Issue by Alatyami** [Dente222/Minecraft-Forge-Tag-List#1]
There are many mods that require a heat source and yet I haven't been able to find a standard tag to implement one. I recommend we add heatsources as a tag. It would include: 

```
{
  "replace": false,
  "values": [
    "minecraft:lava",
    "minecraft:fire",
    "minecraft:magma_block"
  ]
}
```

**Comment by Dente222** [comment]
Added to the Misc section

**Comment by Alatyami** [comment]
Adding to the misc tag doesn't provide a common tag for identifying heat sources like a fire or a heated furnace. By using the misc tag a glass pane would return true for a heatsource.
